flyStereo:
  # Global Commands
  wait_for_start_command: false
  R_imu_cam0: [0.0, 0.0, 0.0]

  replay_mode:
    enable: false
    replay_dir: /root/flyStereo/build_docker/replay/run084
    replay_speed_multiplier: 1
    enable_serial_replay: false

  record_mode:
    enable: true  # Enables logging
    log_root_dir: /root/flyStereo/build_docker/replay
    outputs:
      SQL_database: false
      trajectory: true

  mavlink_reader:
    # device: /root/flyStereo/replay_data/flight/8_15_20/run005/imu.dat

  vio:
    vio_calibration: [-0.0021, 0.0004, -0.0012]
    kalman_filter:
      dt: 0.2
      sigma_a: 1.0
      f: [0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      h:  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
      r:  [0.001, 0.0, 0.0,
          0.0, 0.001, 0.0,
          0.0, 0.0, 0.001]

  ImageSinkCam0:
    framerate: 20
    width: 1280
    height: 720
    sink_pipeline: "appsrc ! videoconvert ! queue ! xvimagesink sync=false "
    # sink_pipeline: "appsrc ! videoconvert ! tee name=t ! queue ! autovideosink t. ! queue ! videoconvert ! x264enc tune=zerolatency ! qtmux ! filesink location=/root/flyStereo/build_docker/replay/run023/cam1_annotated.mp4"
    # sink_pipeline: "appsrc ! videoconvert ! queue ! videoconvert ! x264enc tune=zerolatency ! qtmux ! filesink location=/root/flyStereo/build_docker/replay/run023/cam1_annotated.mp4"


  ImageSinkCam1:
    framerate: 20
    width: 1280
    height: 720
    sink_pipeline: "appsrc ! videoconvert ! queue ! xvimagesink sync=false "
    # sink_pipeline: "appsrc ! videoconvert ! tee name=t ! queue ! autovideosink t. ! queue ! videoconvert ! x264enc tune=zerolatency ! qtmux ! filesink location=/root/flyStereo/build_docker/replay/run023/cam1_annotated.mp4"
    # sink_pipeline: "appsrc ! videoconvert ! queue ! videoconvert ! x264enc tune=zerolatency ! qtmux ! filesink location=/root/flyStereo/build_docker/replay/run023/cam1_annotated.mp4"

  stereo_calibration:
    # Calibration after remounting Camera
    K0:
       rows: 3
       cols: 3
       dt: d
       data: [798.849792, 0.000000, 643.737549,
              0.000000, 798.849792, 375.421753,
              0.000000, 0.000000, 1.000000]
    D0:
       rows: 0
       cols: 1
       dt: d
       data: [  ]
    K1:
       rows: 3
       cols: 3
       dt: d
       data: [798.849792, 0.000000, 643.737549,
              0.000000, 798.849792, 375.421753,
              0.000000, 0.000000, 1.000000]

    D1:
       rows: 0
       cols: 1
       dt: d
       data: []
    R:
       rows: 3
       cols: 3
       dt: d
       data: [0.999849, -0.001484, -0.017304,
              0.001429, 0.999994, -0.003185,
              0.017309, 0.003159, 0.999845]

    T:
       rows: 3
       cols: 1
       dt: d
       data: [-0.07485001, -0.00037700, -0.00000521]
    E:
       rows: 3
       cols: 3
       dt: d
       data: [ -6.6711931189522534e-04, -1.8881446922506674e-03,
           1.3225146160001761e-01, -2.1640485903113523e-03,
           -7.0361287805176975e-05, 1.1401013597424040e-03,
           -1.3221074499902563e-01, -3.3026595611717201e-03,
           -7.3287162022982254e-04 ]
    F:
       rows: 3
       cols: 3
       dt: d
       data: [ 3.9024333072926777e-07, 1.1048593366057523e-06,
           -5.4384653353871965e-02, 1.2654308739328487e-06,
           4.1157116390442146e-08, -1.2964087997648973e-03,
           5.3113014408008898e-02, 6.0639350746943864e-04, 1. ]
