flyStereo:
  # Global Commands
  wait_for_start_command: false

  replay_mode:
    enable: true
    replay_dir: /root/flyStereo/replay_data/flight/11_21_20/run013
    replay_speed_multiplier: 1
    enable_serial_replay: false

  record_mode:
    enable: true  # Enables logging
    log_root_dir: /root/flyStereo/build_docker/replay
    outputs:
      SQL_database: false
      trajectory: true

  mavlink_reader:
    # device: /root/flyStereo/replay_data/flight/8_15_20/run005/imu.dat

  vio:
    vio_calibration: [-0.0021, 0.0004, -0.0012]
    kalman_filter:
      dt: 0.2
      sigma_a: 1.0
      f: [0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      h:  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
      r:  [0.001, 0.0, 0.0,
          0.0, 0.001, 0.0,
          0.0, 0.0, 0.001]

  image_processor:
    rate_limit_fps: 11
    draw_points_to_frame: true
    max_error_counter: 10

    thresholds:
      stereo_threshold: 45
      ransac_threshold: 10

    goodFeaturesToTrack:
      max_corners: 300
      quality_level: 0.15
      min_dist: 15.0

    calcOpticalFlowPyrLK:
      window_size: 21
      max_pyramid_level: 3
      max_iters: 30

    binning:
      bins_width: 20
      bins_height: 15
      max_pts_in_bin: 1

  sensor_interface:
    # Minumum time before two triggers are allowed
    min_camera_dt_ms: 40

    CameraTrigger:
      replay_mode: true
      chip_num: 0
      pin_num: 79
      auto_trigger_async: false
      auto_trigger_async_rate_hz: 20
    Camera0:
      auto_exposure:
        enable: false
        auto_exposure_update_percentage: 0.1
        pixel_range_limits: [58, 98]
        exposure_limits: [51, 2500]
        num_frames_to_calc: 1

      gstreamer_pipeline:
        enable: false

      src_pipeline: "filesrc location=/root/flyStereo/replay_data/flight/8_15_20/run005/cam0.mp4 ! decodebin ! videoconvert ! video/x-raw, format=(string)GRAY8 ! appsink sync=true "
      # src_pipeline: "filesrc location=/root/flyStereo/replay_data/test_replay/cam0.mp4 ! decodebin ! videoconvert ! appsink "

      enable_videoflip: false
      flip_method: -1
      device_num: 0
      hardware_trigger_mode: true
      gain: 1
      exposure_time: 500
    ImageSinkCam0:
      framerate: 20
      width: 1280
      height: 720
      sink_pipeline: "appsrc ! videoconvert ! queue ! videoconvert ! x264enc tune=zerolatency ! qtmux ! filesink location=/root/flyStereo/build_docker/replay/run023/cam0_annotated.mp4"
      # sink_pipeline: "appsrc ! videoconvert ! queue ! xvimagesink sync=false "
      # sink_pipeline: "appsrc ! videoconvert ! tee name=t ! queue ! autovideosink t. ! queue ! videoconvert ! x264enc tune=zerolatency ! qtmux ! filesink location=/root/flyStereo/build_docker/replay/run023/cam0_annotated.mp4"

    Camera1:
      auto_exposure:
        enable: false
        auto_exposure_update_percentage: 0.1
        pixel_range_limits: [70, 110]
        exposure_limits: [10, 2500]
        num_frames_to_calc: 1

      gstreamer_pipeline:
        enable: false

      src_pipeline: "filesrc location=/root/flyStereo/replay_data/flight/8_15_20/run005/cam1.mp4 ! decodebin ! videoconvert ! video/x-raw, format=(string)GRAY8 ! appsink sync=true "


      device_num: 1
      enable_videoflip: false
      flip_method: -1
      hardware_trigger_mode: true
      gain: 1
      exposure_time: 500
    ImageSinkCam0:
      framerate: 20
      width: 1280
      height: 720
      sink_pipeline: "appsrc ! videoconvert ! queue ! xvimagesink sync=false "
      # sink_pipeline: "appsrc ! videoconvert ! tee name=t ! queue ! autovideosink t. ! queue ! videoconvert ! x264enc tune=zerolatency ! qtmux ! filesink location=/root/flyStereo/build_docker/replay/run023/cam1_annotated.mp4"
      # sink_pipeline: "appsrc ! videoconvert ! queue ! videoconvert ! x264enc tune=zerolatency ! qtmux ! filesink location=/root/flyStereo/build_docker/replay/run023/cam1_annotated.mp4"

  stereo_calibration:
    R_imu_cam0: [0.0, 3.1415926535, 0.0]
    # Calibration after remounting Camera
    K0:
       rows: 3
       cols: 3
       dt: d
       data: [ 6.9423990346645769e+02, 0., 6.4624479627350570e+02, 0.,
           6.9401655670279729e+02, 3.8383485359306906e+02, 0., 0., 1. ]
    D0:
       rows: 8
       cols: 1
       dt: d
       data: [ 1.4368887453753596e+00, 1.1208857703465060e+00,
           3.9770691373894568e-04, -1.8907857082627497e-04,
           9.1422681283065674e-02, 1.8116512256004902e+00,
           1.5921279733009270e+00, 3.9253025988500673e-01 ]
    K1:
       rows: 3
       cols: 3
       dt: d
       data: [ 6.9543805938753951e+02, 0., 6.5534887751462441e+02, 0.,
           6.9569521027497433e+02, 3.2854110262522761e+02, 0., 0., 1. ]
    D1:
       rows: 8
       cols: 1
       dt: d
       data: [ 8.8150121657853686e-01, 1.3122637354594775e-02,
           3.2722693793831758e-04, -1.5659808615470528e-05,
           -1.1656382252949139e-02, 1.2615557633660002e+00,
           2.4734706895213193e-01, -3.5222413544851269e-02 ]
    R:
       rows: 3
       cols: 3
       dt: d
       data: [ 9.9985376283481753e-01, 1.6267100225257715e-02,
           5.2758312442480731e-03, -1.6420697227381605e-02,
           9.9939958710505661e-01, 3.0509441109418844e-02,
           -4.7763634307939531e-03, -3.0591612322724265e-02,
           9.9952055487012026e-01 ]
    T:
       rows: 3
       cols: 1
       dt: d
       data: [ -1.1520434914861941e-03, 1.3224900207555385e-01,
           -2.1588617177255545e-03 ]
    E:
       rows: 3
       cols: 3
       dt: d
       data: [ -6.6711931189522534e-04, -1.8881446922506674e-03,
           1.3225146160001761e-01, -2.1640485903113523e-03,
           -7.0361287805176975e-05, 1.1401013597424040e-03,
           -1.3221074499902563e-01, -3.3026595611717201e-03,
           -7.3287162022982254e-04 ]
    F:
       rows: 3
       cols: 3
       dt: d
       data: [ 3.9024333072926777e-07, 1.1048593366057523e-06,
           -5.4384653353871965e-02, 1.2654308739328487e-06,
           4.1157116390442146e-08, -1.2964087997648973e-03,
           5.3113014408008898e-02, 6.0639350746943864e-04, 1. ]
