
#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Rectified Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 798.849792
Camera1.fy: 798.849792
Camera1.cx: 643.737549
Camera1.cy: 375.421753

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

Camera2.fx: 798.849792
Camera2.fy: 798.849792
Camera2.cx: 643.737549
Camera2.cy: 375.421753

Camera2.k1: 0.0
Camera2.k2: 0.0
Camera2.p1: 0.0
Camera2.p2: 0.0


Stereo.T_c1_c2:
  rows: 4
  cols: 4
  dt: f
  data: [0.999849, -0.001484, -0.017304, -0.07485001,
        0.001429, 0.999994, -0.003185, -0.00037700,
        0.017309, 0.003159, 0.999845, -0.00000521,
        0.000000, 0.000000, 0.000000, 1.000000]

# Transformation from body-frame (imu) to left camera
IMU.T_b_c1:
   rows: 4
   cols: 4
   dt: f
   data: [1.0, 0.0, 0.0, -0.005,
          0.0, 1.0, 0.0, -0.005,
          0.0, 0.0, 1.0, 0.0117,
          0.0, 0.0, 0.0, 1.0]

# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 0
# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 1e-3 # 2.44e-4 #1e-3 # rad/s^0.5
IMU.NoiseAcc: 1e-2 # 1.47e-3 #1e-2 # m/s^1.5
IMU.GyroWalk: 1e-6 # rad/s^1.5
IMU.AccWalk: 1e-4 # m/s^2.5
IMU.Frequency: 200.0

Stereo.b: 0.07485001

# Camera resolution
Camera.width: 1280
Camera.height: 720

# Camera frames per second
Camera.fps: 12

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
# Viewer.KeyFrameSize: 0.05
# Viewer.KeyFrameLineWidth: 1.0
# Viewer.GraphLineWidth: 0.9
# Viewer.PointSize: 2.0
# Viewer.CameraSize: 0.08
# Viewer.CameraLineWidth: 3.0
# Viewer.ViewpointX: 0.0
# Viewer.ViewpointY: -0.7
# Viewer.ViewpointZ: -3.5
# Viewer.ViewpointF: 500.0

Viewer.KeyFrameSize: 0.3
Viewer.KeyFrameLineWidth: 2.0
Viewer.GraphLineWidth: 1.0
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.7
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: -10.0
Viewer.ViewpointY: -10.0
Viewer.ViewpointZ: -10.0
Viewer.ViewpointF: 2000.0
