fly_stereo:
  mavlink_reader:
    # device: /dev/ttyTHS1
    # replay_mode: false
    device: /root/fly_stereo/replay_data/rotation/imu.dat
    replay_mode: true
    # replay_imu_data_file: /home/msardonini/git/fly_stereo/replay_data/test_replay/imu.dat

  vio:
    image_width: 1280
    image_height: 720
    bins_width: 40
    bins_height: 30
    max_pts_in_bin: 3

  image_processor:
    CameraTrigger:
      replay_mode: true
      chip_num: 0
      pin_num: 79
      auto_trigger_async: false
      auto_trigger_async_rate_hz: 20
    Camera0:
      # auto_exposure:
      #   pixel_range_limits: [108, 148]
      #   exposure_limits: [1250, 2500]
      #   num_frames_to_calc: 3
      device_num: 0
      src_pipeline: "filesrc location=/root/fly_stereo/replay_data/rotation/cam0.mp4 ! decodebin ! videoconvert ! video/x-raw, format=(string)GRAY8 ! appsink sync=true "
      # src_pipeline: "filesrc location=/root/fly_stereo/replay_data/test_replay/cam0.mp4 ! decodebin ! videoconvert ! appsink "
      sink_pipeline: "appsrc ! videoconvert ! videoflip method=rotate-180 ! autovideosink "
      framerate: 20
      width: 1280
      height: 720
      flip_method: 0
      hardware_trigger_mode: true
      gain: 3
      exposure_time: 1500
    Camera1:
      # auto_exposure:
      #   pixel_range_limits: [108, 148]
      #   exposure_limits: [1250, 2500]
      #   num_frames_to_calc: 3
      device_num: 1
      src_pipeline: "filesrc location=/root/fly_stereo/replay_data/rotation/cam1.mp4 ! decodebin ! videoconvert ! video/x-raw, format=(string)GRAY8 ! appsink sync=true "
      # src_pipeline: "filesrc location=/root/fly_stereo/replay_data/test_replay/cam1.mp4 ! decodebin ! videoconvert ! appsink max-buffers=1"
      sink_pipeline: "appsrc ! videoconvert ! videoflip method=rotate-180 ! autovideosink "
      framerate: 20
      width: 1280
      height: 720
      flip_method: 1
      hardware_trigger_mode: true
      gain: 3
      exposure_time: 1500
    draw_points_to_frame: true
    max_error_counter: 2
    stereo_threshold: 50
    ransac_threshold: 5

    goodFeaturesToTrack:
      max_corners: 300
      quality_level: 0.15
      min_dist: 15.0

    calcOpticalFlowPyrLK:
      window_size: 21
      max_pyramid_level: 5

  stereo_calibration:
    # 3.14159265359
    # 4.71238898038
    # debug_vec: [1.57, 0, 4.7123]
    debug_vec: [0, 0, 4.71238898038]
    K0: !!opencv-matrix
       rows: 3
       cols: 3
       dt: d
       data: [ 7.4918440521802654e+02, 0., 6.4058899720317379e+02, 0.,
           7.4708619102983243e+02, 3.7256841238281532e+02, 0., 0., 1. ]
    D0: !!opencv-matrix
       rows: 1
       cols: 5
       dt: d
       data: [ -3.5987375613709977e-01, 1.5251829704894446e-01,
           1.4681485630212356e-03, 5.7935704747067340e-04,
           -3.3292248102409577e-02 ]
    K1: !!opencv-matrix
       rows: 3
       cols: 3
       dt: d
       data: [ 6.9213104490896023e+02, 0., 6.3797203446567494e+02, 0.,
           6.8750698329914508e+02, 3.8994904877180983e+02, 0., 0., 1. ]
    D1: !!opencv-matrix
       rows: 1
       cols: 5
       dt: d
       data: [ -3.3803988649240801e-01, 1.3219480012774543e-01,
           -9.0492198383922856e-05, 1.0586231964448353e-03,
           -2.7376380712040953e-02 ]
    R: !!opencv-matrix
       rows: 3
       cols: 3
       dt: d
       data: [ 9.9973785332478338e-01, -1.2948157899017558e-02,
           1.8883056865239542e-02, 1.3022339346497649e-02,
           9.9990794398589533e-01, -3.8108046190075020e-03,
           -1.8831975666361196e-02, 4.0557072036451194e-03,
           9.9981443674892989e-01 ]
    T: !!opencv-matrix
       rows: 3
       cols: 1
       dt: d
       data: [ 4.0446847703199479e-02, 2.0614056343742607e-01,
           -7.2784365782692012e-02 ]
    E: !!opencv-matrix
       rows: 3
       cols: 3
       dt: d
       data: [ -2.9342113641617667e-03, 7.3613711312185554e-02,
           2.0582494432698098e-01, -7.2003591551466656e-02,
           7.7838288913954366e-04, -4.1813733572619104e-02,
           -2.0555981179780650e-01, 4.3112264892397063e-02,
           -4.0466990156730808e-03 ]
    F: !!opencv-matrix
       rows: 3
       cols: 3
       dt: d
       data: [ 2.9845223280547574e-07, -7.5086207766959133e-06,
           -1.3078192030037322e-02, 7.3730777382164907e-06,
           -7.9929289647790340e-08, -1.4855699330836188e-03,
           1.1405852197717637e-02, 1.7778370466344754e-03, 1. ]